# Parameters
mu_max: 0.2 # [1/h]  0.3514 0.2
m_s: 0.1 # from 2015 Shen
Ks: 7.0  # [g/L]
Ks_qs: 0.035  # [g/L] 
Ki: 7.150  # [g/L]
qs_max: 0.57  # [g_substrate/g_biomass*h]
Yxs:  0.4857 #[g_biomass/g_substrate] from 2015 Shen: 0.5264
c_glu_feed: 350 # [g/L]
lag: 0.0057 
X_max: 19.2 # [g/L]

# Initial conditions
X0: 0.5  # Initial biomass [g/L]
S0: 10.0  # Initial substrate concentration [g/L]
V0: 1.0 # Initial volume in the reactor [L]